// 民族
export const RaceArr = [
  { id: 1, text: "汉族" },
  { id: 2, text: "蒙古族" },
  { id: 3, text: "回族" },
  { id: 4, text: "藏族" },
  { id: 5, text: "维吾尔族" },
  { id: 6, text: "苗族" },
  { id: 7, text: "彝族" },
  { id: 8, text: "壮族" },
  { id: 9, text: "布依族" },
  { id: 10, text: "朝鲜族" },
  { id: 11, text: "满族" },
  { id: 12, text: "侗族" },
  { id: 13, text: "瑶族" },
  { id: 14, text: "白族" },
  { id: 15, text: "土家族" },
  { id: 16, text: "哈尼族" },
  { id: 17, text: "哈萨克族" },
  { id: 18, text: "傣族" },
  { id: 19, text: "黎族" },
  { id: 20, text: "傈僳族" },
  { id: 21, text: "佤族" },
  { id: 22, text: "畲族" },
  { id: 23, text: "高山族" },
  { id: 24, text: "拉祜族" },
  { id: 25, text: "水族" },
  { id: 26, text: "东乡族" },
  { id: 27, text: "纳西族" },
  { id: 28, text: "景颇族" },
  { id: 29, text: "柯尔克孜族" },
  { id: 30, text: "土族" },
  { id: 31, text: "达斡尔族" },
  { id: 32, text: "仫佬族" },
  { id: 33, text: "羌族" },
  { id: 34, text: "布朗族" }
];
